services:
  frontend:
    build: .
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - REACT_APP_API_BASE_URL=http://backend:5000

  backend:
    image: seat_booking_api-flask_app:latest
    container_name: seat_booking_api
    ports:
      - "5000:5000"
    restart: unless-stopped
