services:
  frontend:
    build: .
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
#    environment:
#      - REACT_APP_API_BASE_URL=http://backend:5000
    env_file:
      - .env

  backend:
    image: seat-booking-backend-flask_app:latest
    container_name: backend  # Keep it consistent with React API calls
#    ports:
#      - "5000:5000"
    restart: unless-stopped
